### ISSUE TITLE
jpeg not rendering during export

### ISSUE THREAD

**Issue by blueteafrog** [sawhney17/logseq-pdf-export#26] opened 2022-06-29 00:51 UTC
During export jpeg format not rendering. png is working fine.

OS: MacOS 12.4
Logseq v 0.7.5

![Screen Shot 2022-06-28 at 5 46 40 PM](https://user-images.githubusercontent.com/7694090/176327954-7b366a54-2b0b-49e0-8b3e-44b87f9ec964.png)

**Comment by sdasda7777** [comment] 2024-02-08 11:13
That kind of looks to me like there is a code block above it, no? This issue with code blocks should be fixed in the latest version, please check if the issue is still relevant. If so, please provide more information.

**Closed** 2024-06-14 03:10 UTC
